# Generated by Django 5.1.12 on 2026-08-10 00:37
# Django's migration serializer emits compact field tuples; keep its generated layout.
# ruff: noqa: E501

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfx', '0010_process_heartbeats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family', models.CharField(choices=[('nfe', 'NF-e'), ('nfse', 'NFS-e')], max_length=8)),
                ('role', models.CharField(max_length=16)),
                ('category', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=64)),
                ('flow', models.CharField(max_length=64)),
                ('identity_kind', models.CharField(max_length=32)),
                ('normalized_identity', models.CharField(max_length=255)),
                ('identity_key', models.CharField(editable=False, max_length=1024, unique=True)),
                ('emitted_at', models.DateTimeField()),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('competence', models.DateField()),
                ('situation', models.CharField(choices=[('authorized', 'Authorized'), ('cancelled', 'Cancelled'), ('unknown', 'Unknown')], max_length=16)),
                ('state', models.CharField(choices=[('persisted', 'Persisted'), ('conflict', 'Conflict')], default='persisted', max_length=16)),
                ('origin_execution_ref', models.CharField(max_length=128)),
                ('correlation_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='nfx.company')),
            ],
            options={
                'db_table': 'nfx_document',
            },
        ),
        migrations.CreateModel(
            name='DocumentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family', models.CharField(choices=[('nfe', 'NF-e'), ('nfse', 'NFS-e')], max_length=8)),
                ('role', models.CharField(default='evento', max_length=16)),
                ('category', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=64)),
                ('flow', models.CharField(max_length=64)),
                ('identity_kind', models.CharField(max_length=32)),
                ('normalized_identity', models.CharField(max_length=255)),
                ('identity_key', models.CharField(editable=False, max_length=1024, unique=True)),
                ('occurred_at', models.DateTimeField()),
                ('situation', models.CharField(choices=[('authorized', 'Authorized'), ('cancelled', 'Cancelled'), ('unknown', 'Unknown')], max_length=16)),
                ('relationship_type', models.CharField(choices=[('event', 'Event'), ('substitution', 'Substitution')], max_length=16)),
                ('state', models.CharField(choices=[('persisted', 'Persisted'), ('conflict', 'Conflict')], default='persisted', max_length=16)),
                ('origin_execution_ref', models.CharField(max_length=128)),
                ('correlation_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='nfx.document')),
            ],
            options={
                'db_table': 'nfx_document_event',
            },
        ),
        migrations.CreateModel(
            name='DocumentEventEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('digest', models.CharField(max_length=64)),
                ('size_bytes', models.BigIntegerField()),
                ('conflicting', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_event_evidence', to='nfx.artifact')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='nfx.documentevent')),
            ],
            options={
                'db_table': 'nfx_document_event_evidence',
            },
        ),
        migrations.CreateModel(
            name='DocumentEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('digest', models.CharField(max_length=64)),
                ('size_bytes', models.BigIntegerField()),
                ('conflicting', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_evidence', to='nfx.artifact')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='nfx.document')),
            ],
            options={
                'db_table': 'nfx_document_evidence',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'competence'], name='nfx_document_company_comp_ix'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['family', 'emitted_at'], name='nfx_document_family_emit_ix'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['normalized_identity'], name='nfx_document_identity_ix'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['situation', 'state'], name='nfx_document_situation_ix'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['source', 'flow', 'category'], name='nfx_document_context_ix'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('emitted_at__isnull', False)), name='nfx_document_emitted_required_ck'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('origin_execution_ref__regex', '^[A-Za-z0-9_.:/-]{1,128}$')), name='nfx_document_origin_ref_ck'),
        ),
        migrations.AddIndex(
            model_name='documentevent',
            index=models.Index(fields=['parent_document', 'occurred_at'], name='nfx_event_parent_time_ix'),
        ),
        migrations.AddIndex(
            model_name='documentevent',
            index=models.Index(fields=['family', 'relationship_type'], name='nfx_event_family_rel_ix'),
        ),
        migrations.AddIndex(
            model_name='documentevent',
            index=models.Index(fields=['normalized_identity'], name='nfx_event_identity_ix'),
        ),
        migrations.AddConstraint(
            model_name='documentevent',
            constraint=models.CheckConstraint(condition=models.Q(('origin_execution_ref__regex', '^[A-Za-z0-9_.:/-]{1,128}$')), name='nfx_event_origin_ref_ck'),
        ),
        migrations.AddIndex(
            model_name='documenteventevidence',
            index=models.Index(fields=['event', 'digest'], name='nfx_evt_evidence_digest_ix'),
        ),
        migrations.AddConstraint(
            model_name='documenteventevidence',
            constraint=models.UniqueConstraint(fields=('event', 'artifact'), name='nfx_event_evidence_artifact_uq'),
        ),
        migrations.AddConstraint(
            model_name='documenteventevidence',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gte', 0)), name='nfx_event_evidence_size_ck'),
        ),
        migrations.AddIndex(
            model_name='documentevidence',
            index=models.Index(fields=['document', 'digest'], name='nfx_doc_evidence_digest_ix'),
        ),
        migrations.AddConstraint(
            model_name='documentevidence',
            constraint=models.UniqueConstraint(fields=('document', 'artifact'), name='nfx_document_evidence_artifact_uq'),
        ),
        migrations.AddConstraint(
            model_name='documentevidence',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gte', 0)), name='nfx_document_evidence_size_ck'),
        ),
    ]
