# Generated by Django 5.1.12 on 2026-08-10 01:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfx', '0011_document_documentevent_documenteventevidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyflow',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='companyflow',
            name='collection_state',
            field=models.CharField(default='idle', max_length=16),
        ),
        migrations.AddField(
            model_name='companyflow',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyflow',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyflow',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyflow',
            name='next_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyflow',
            name='progress_current',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyflow',
            name='progress_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyflow',
            name='safe_error',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='initialcollectionrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initialcollectionrequest',
            name='safe_error',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='initialcollectionrequest',
            name='state',
            field=models.CharField(
                choices=[('queued', 'Queued'), ('consumed', 'Consumed'), ('blocked', 'Blocked')],
                default='queued', max_length=16,
            ),
        ),
        migrations.CreateModel(
            name='CollectionExecution',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False,
                    ),
                ),
                ('family', models.CharField(max_length=8)),
                (
                    'requested_scope',
                    models.CharField(
                        choices=[('completa', 'Completa'), ('nfe', 'NF-e'), ('nfse', 'NFS-e')],
                        max_length=8,
                    ),
                ),
                (
                    'origin',
                    models.CharField(
                        choices=[
                            ('automatica', 'Automática'), ('manual', 'Manual'), ('retry', 'Retry'),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('queued', 'Queued'),
                            ('running', 'Running'),
                            ('concluded', 'Concluded'),
                            ('empty', 'Valid empty'),
                            ('partial', 'Partial'),
                            ('retrying', 'Retrying'),
                            ('cooldown', 'Cooldown'),
                            ('blocked', 'Blocked'),
                            ('failed', 'Failed'),
                        ],
                        default='queued', max_length=16,
                    ),
                ),
                ('correlation_id', models.CharField(max_length=128)),
                ('safe_summary', models.JSONField(default=dict)),
                ('safe_error', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='collection_executions', to='nfx.company',
                    ),
                ),
                (
                    'effective_policy',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                        related_name='collection_executions', to='nfx.jobpolicy',
                    ),
                ),
                (
                    'job',
                    models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                        related_name='collection_execution', to='nfx.job',
                    ),
                ),
                (
                    'requester',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                        related_name='collection_executions', to='nfx.user',
                    ),
                ),
                (
                    'retry_of',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                        related_name='retries', to='nfx.collectionexecution',
                    ),
                ),
            ],
            options={
                'db_table': 'nfx_collection_execution',
            },
        ),
        migrations.AddField(
            model_name='companyflow',
            name='active_execution',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='active_flow_rows', to='nfx.collectionexecution',
            ),
        ),
        migrations.AddIndex(
            model_name='companyflow',
            index=models.Index(
                fields=['collection_state', 'next_scheduled_at'], name='nfx_flow_collection_due_ix',
            ),
        ),
        migrations.AddIndex(
            model_name='collectionexecution',
            index=models.Index(
                fields=['company', 'family', 'created_at'], name='nfx_coll_exec_company_ix',
            ),
        ),
        migrations.AddIndex(
            model_name='collectionexecution',
            index=models.Index(fields=['state', 'created_at'], name='nfx_coll_exec_state_ix'),
        ),
        migrations.AddIndex(
            model_name='collectionexecution',
            index=models.Index(fields=['correlation_id'], name='nfx_coll_exec_corr_ix'),
        ),
        migrations.AddConstraint(
            model_name='collectionexecution',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('state__in', ('queued', 'running', 'retrying', 'cooldown', 'partial')),
                ),
                fields=('company', 'family'), name='nfx_collection_active_company_family_uq',
            ),
        ),
        migrations.AddConstraint(
            model_name='collectionexecution',
            constraint=models.CheckConstraint(
                condition=models.Q(('family__in', ('nfe', 'nfse'))),
                name='nfx_collection_family_ck',
            ),
        ),
        migrations.AddConstraint(
            model_name='collectionexecution',
            constraint=models.CheckConstraint(
                condition=models.Q(('correlation_id__regex', '^[A-Za-z0-9_.:/-]{1,128}$')),
                name='nfx_collection_correlation_ck',
            ),
        ),
    ]
