# Generated by Django 5.1.12 on 2026-08-10 12:24
# ruff: noqa: E501

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfx', '0012_companyflow_blocked_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family', models.CharField(max_length=8)),
                ('flow', models.CharField(max_length=64)),
                ('page_key', models.CharField(max_length=160)),
                ('request_cursor', models.CharField(blank=True, max_length=128)),
                ('request_nsu', models.CharField(blank=True, max_length=128)),
                ('next_cursor', models.CharField(blank=True, max_length=128)),
                ('next_nsu', models.CharField(blank=True, max_length=128)),
                ('adapter_outcome', models.CharField(max_length=32)),
                ('coverage', models.CharField(max_length=16)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('empty', 'Valid empty'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=16)),
                ('safe_error', models.CharField(blank=True, max_length=64)),
                ('unit_count', models.PositiveIntegerField(default=0)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_pages', to='nfx.company')),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_pages', to='nfx.collectionexecution')),
            ],
            options={
                'db_table': 'nfx_ingestion_page',
            },
        ),
        migrations.CreateModel(
            name='IngestionCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family', models.CharField(max_length=8)),
                ('flow', models.CharField(max_length=64)),
                ('cursor', models.CharField(blank=True, max_length=128)),
                ('nsu', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_checkpoints', to='nfx.company')),
                ('last_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkpoint_completions', to='nfx.ingestionpage')),
            ],
            options={
                'db_table': 'nfx_ingestion_checkpoint',
            },
        ),
        migrations.CreateModel(
            name='ReceivedUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family', models.CharField(max_length=8)),
                ('flow', models.CharField(max_length=64)),
                ('identity', models.CharField(max_length=128)),
                ('kind', models.CharField(max_length=16)),
                ('parent_identity', models.CharField(blank=True, max_length=128)),
                ('content_hash', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('persisted', 'Persisted'), ('replay', 'Replay'), ('quarantine', 'Quarantine'), ('conflict', 'Conflict'), ('failed', 'Failed')], max_length=16)),
                ('safe_reason', models.CharField(blank=True, max_length=64)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('terminal_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_units', to='nfx.artifact')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_units', to='nfx.company')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_units', to='nfx.document')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_units', to='nfx.documentevent')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='nfx.ingestionpage')),
            ],
            options={
                'db_table': 'nfx_received_unit',
            },
        ),
        migrations.AddIndex(
            model_name='ingestionpage',
            index=models.Index(fields=['company', 'family', 'flow', 'state'], name='nfx_ingest_page_state_ix'),
        ),
        migrations.AddIndex(
            model_name='ingestionpage',
            index=models.Index(fields=['state', 'created_at'], name='nfx_ingest_page_age_ix'),
        ),
        migrations.AddConstraint(
            model_name='ingestionpage',
            constraint=models.UniqueConstraint(fields=('company', 'family', 'flow', 'page_key'), name='nfx_ingest_page_scope_key_uq'),
        ),
        migrations.AddConstraint(
            model_name='ingestionpage',
            constraint=models.CheckConstraint(condition=models.Q(('family__in', ('nfe', 'adn', 'nfse'))), name='nfx_ingest_page_family_ck'),
        ),
        migrations.AddConstraint(
            model_name='ingestionpage',
            constraint=models.CheckConstraint(condition=models.Q(('request_cursor', ''), ('request_nsu', ''), _connector='OR'), name='nfx_ingest_page_request_position_ck'),
        ),
        migrations.AddConstraint(
            model_name='ingestionpage',
            constraint=models.CheckConstraint(condition=models.Q(('next_cursor', ''), ('next_nsu', ''), _connector='OR'), name='nfx_ingest_page_next_position_ck'),
        ),
        migrations.AddConstraint(
            model_name='ingestionpage',
            constraint=models.CheckConstraint(condition=models.Q(('flow__regex', '^[A-Za-z0-9_.:/-]{1,64}$')), name='nfx_ingest_page_flow_ck'),
        ),
        migrations.AddIndex(
            model_name='ingestioncheckpoint',
            index=models.Index(fields=['company', 'family', 'updated_at'], name='nfx_ingest_cp_age_ix'),
        ),
        migrations.AddConstraint(
            model_name='ingestioncheckpoint',
            constraint=models.UniqueConstraint(fields=('company', 'family', 'flow'), name='nfx_ingest_checkpoint_scope_uq'),
        ),
        migrations.AddConstraint(
            model_name='ingestioncheckpoint',
            constraint=models.CheckConstraint(condition=models.Q(('family__in', ('nfe', 'adn', 'nfse'))), name='nfx_ingest_checkpoint_family_ck'),
        ),
        migrations.AddConstraint(
            model_name='ingestioncheckpoint',
            constraint=models.CheckConstraint(condition=models.Q(('cursor', ''), ('nsu', ''), _connector='OR'), name='nfx_ingest_checkpoint_position_ck'),
        ),
        migrations.AddConstraint(
            model_name='ingestioncheckpoint',
            constraint=models.CheckConstraint(condition=models.Q(('flow__regex', '^[A-Za-z0-9_.:/-]{1,64}$')), name='nfx_ingest_checkpoint_flow_ck'),
        ),
        migrations.AddIndex(
            model_name='receivedunit',
            index=models.Index(fields=['company', 'family', 'flow', 'identity'], name='nfx_received_unit_lookup_ix'),
        ),
        migrations.AddIndex(
            model_name='receivedunit',
            index=models.Index(fields=['state', 'last_attempt_at'], name='nfx_received_unit_retry_ix'),
        ),
        migrations.AddIndex(
            model_name='receivedunit',
            index=models.Index(fields=['content_hash'], name='nfx_received_unit_hash_ix'),
        ),
        migrations.AddConstraint(
            model_name='receivedunit',
            constraint=models.UniqueConstraint(fields=('page', 'identity'), name='nfx_received_unit_page_identity_uq'),
        ),
        migrations.AddConstraint(
            model_name='receivedunit',
            constraint=models.CheckConstraint(condition=models.Q(('family__in', ('nfe', 'adn', 'nfse'))), name='nfx_received_unit_family_ck'),
        ),
        migrations.AddConstraint(
            model_name='receivedunit',
            constraint=models.CheckConstraint(condition=models.Q(('content_hash__regex', '^[0-9a-f]{64}$')), name='nfx_received_unit_hash_ck'),
        ),
        migrations.AddConstraint(
            model_name='receivedunit',
            constraint=models.CheckConstraint(condition=models.Q(('flow__regex', '^[A-Za-z0-9_.:/-]{1,64}$')), name='nfx_received_unit_flow_ck'),
        ),
    ]
