# Generated by Django 5.1.12 on 2026-08-10 13:30

from django.db import migrations, models

# ruff: noqa: E501


class Migration(migrations.Migration):

    dependencies = [
        ('nfx', '0013_ingestionpage_ingestioncheckpoint_receivedunit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionexecution',
            name='outcome',
            field=models.CharField(choices=[('success', 'Success'), ('valid_empty', 'Valid empty'), ('no_coverage', 'No coverage'), ('unavailable', 'Unavailable'), ('temporary_failure', 'Temporary failure'), ('cooldown', 'Cooldown'), ('permanent_failure', 'Permanent failure'), ('malformed', 'Malformed'), ('unknown', 'Unknown'), ('partial', 'Partial'), ('quarantine', 'Quarantine'), ('conflict', 'Conflict')], default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='collectionexecution',
            name='recovery',
            field=models.CharField(choices=[('none', 'No action'), ('retry', 'Retry'), ('cooldown', 'Wait for cooldown'), ('blocked', 'Blocked'), ('quarantine', 'Quarantine review'), ('conflict_review', 'Conflict review'), ('reconcile', 'Reconcile position')], default='none', max_length=24),
        ),
        migrations.AddField(
            model_name='ingestionpage',
            name='outcome',
            field=models.CharField(choices=[('success', 'Success'), ('valid_empty', 'Valid empty'), ('no_coverage', 'No coverage'), ('unavailable', 'Unavailable'), ('temporary_failure', 'Temporary failure'), ('cooldown', 'Cooldown'), ('permanent_failure', 'Permanent failure'), ('malformed', 'Malformed'), ('unknown', 'Unknown'), ('partial', 'Partial'), ('quarantine', 'Quarantine'), ('conflict', 'Conflict')], default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='ingestionpage',
            name='recovery',
            field=models.CharField(choices=[('none', 'No action'), ('retry', 'Retry'), ('cooldown', 'Wait for cooldown'), ('blocked', 'Blocked'), ('quarantine', 'Quarantine review'), ('conflict_review', 'Conflict review'), ('reconcile', 'Reconcile position')], default='none', max_length=24),
        ),
        migrations.AddField(
            model_name='receivedunit',
            name='outcome',
            field=models.CharField(choices=[('success', 'Success'), ('valid_empty', 'Valid empty'), ('no_coverage', 'No coverage'), ('unavailable', 'Unavailable'), ('temporary_failure', 'Temporary failure'), ('cooldown', 'Cooldown'), ('permanent_failure', 'Permanent failure'), ('malformed', 'Malformed'), ('unknown', 'Unknown'), ('partial', 'Partial'), ('quarantine', 'Quarantine'), ('conflict', 'Conflict')], default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='receivedunit',
            name='recovery',
            field=models.CharField(choices=[('none', 'No action'), ('retry', 'Retry'), ('cooldown', 'Wait for cooldown'), ('blocked', 'Blocked'), ('quarantine', 'Quarantine review'), ('conflict_review', 'Conflict review'), ('reconcile', 'Reconcile position')], default='none', max_length=24),
        ),
        migrations.AlterField(
            model_name='ingestionpage',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('empty', 'Valid empty'), ('no_coverage', 'No coverage'), ('unavailable', 'Unavailable'), ('retry', 'Retryable'), ('cooldown', 'Cooldown'), ('blocked', 'Blocked'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=16),
        ),
    ]
