# Generated by Django 5.1.12 on 2026-08-10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nfx", "0014_ingestion_failure_state_contract"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdnCoverageSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("none", "No coverage"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("verified_at", models.DateTimeField()),
                ("evidence_reference", models.CharField(blank=True, max_length=128)),
                ("policy_version", models.CharField(max_length=128)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adn_coverage_snapshots",
                        to="nfx.company",
                    ),
                ),
            ],
            options={
                "db_table": "nfx_adn_coverage_snapshot",
                "ordering": ("-verified_at", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="adncoveragesnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(source__regex=r"^[A-Za-z0-9_.:/-]{1,64}$"),
                name="nfx_adn_coverage_source_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="adncoveragesnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(policy_version__regex=r"^[A-Za-z0-9_.:/-]{1,128}$"),
                name="nfx_adn_coverage_policy_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="adncoveragesnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(evidence_reference="")
                | models.Q(evidence_reference__regex=r"^[A-Za-z0-9_.:/-]{1,128}$"),
                name="nfx_adn_coverage_evidence_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="adncoveragesnapshot",
            index=models.Index(
                fields=["company", "status"], name="nfx_adn_coverage_status_ix"
            ),
        ),
        migrations.AddIndex(
            model_name="adncoveragesnapshot",
            index=models.Index(
                fields=["company", "verified_at"], name="nfx_adn_coverage_time_ix"
            ),
        ),
    ]
