# Generated by Django 5.1.12 on 2026-08-11

import uuid

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [("nfx", "0019_document_render")]

    operations = [
        migrations.AlterField(
            model_name="exportitem",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="export_items",
                to="nfx.document",
            ),
        ),
        migrations.CreateModel(
            name="DeletionOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("target_document_id", models.UUIDField()),
                ("scope_hash", models.CharField(max_length=64)),
                ("scope_version", models.CharField(max_length=32)),
                ("reason", models.CharField(max_length=1000)),
                ("correlation_id", models.CharField(max_length=128)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("executing", "Executing"),
                            ("recovery_required", "Recovery required"),
                            ("failed", "Failed"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("current_step", models.CharField(blank=True, max_length=32)),
                ("checkpoint", models.JSONField(default=dict)),
                ("safe_error", models.CharField(blank=True, max_length=64)),
                ("result_code", models.CharField(blank=True, max_length=64)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deletion_operations",
                        to="nfx.user",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deletion_operations",
                        to="nfx.job",
                    ),
                ),
            ],
            options={"db_table": "nfx_deletion_operation"},
        ),
        migrations.CreateModel(
            name="DeletionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("event", "Event"),
                            ("evidence", "Evidence"),
                            ("event_evidence", "Event evidence"),
                            ("render", "Derived render"),
                            ("artifact", "Artifact"),
                        ],
                        max_length=24,
                    ),
                ),
                ("target_id", models.UUIDField()),
                ("artifact_id", models.UUIDField(blank=True, null=True)),
                ("digest_prefix", models.CharField(blank=True, max_length=16)),
                ("expected_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("expected_version", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("recovery_required", "Recovery required"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("safe_error", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="nfx.deletionoperation",
                    ),
                ),
            ],
            options={"db_table": "nfx_deletion_item"},
        ),
        migrations.AddIndex(
            model_name="deletionoperation",
            index=models.Index(
                fields=["target_document_id", "state"], name="nfx_delete_target_state_ix"
            ),
        ),
        migrations.AddIndex(
            model_name="deletionoperation",
            index=models.Index(fields=["state", "requested_at"], name="nfx_delete_state_time_ix"),
        ),
        migrations.AddIndex(
            model_name="deletionoperation",
            index=models.Index(fields=["actor", "requested_at"], name="nfx_delete_actor_time_ix"),
        ),
        migrations.AddConstraint(
            model_name="deletionoperation",
            constraint=models.UniqueConstraint(
                condition=Q(state__in=("pending", "executing", "recovery_required")),
                fields=("target_document_id",),
                name="nfx_delete_active_target_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="deletionoperation",
            constraint=models.CheckConstraint(
                condition=Q(scope_hash__regex=r"^[a-f0-9]{64}$"),
                name="nfx_delete_scope_hash_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="deletionoperation",
            constraint=models.CheckConstraint(
                condition=Q(scope_version="scope-v1"), name="nfx_delete_scope_version_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="deletionoperation",
            constraint=models.CheckConstraint(
                condition=Q(reason__gt=""), name="nfx_delete_reason_ck"
            ),
        ),
        migrations.AddIndex(
            model_name="deletionitem",
            index=models.Index(fields=["operation", "state"], name="nfx_delete_item_state_ix"),
        ),
        migrations.AddIndex(
            model_name="deletionitem",
            index=models.Index(fields=["artifact_id", "state"], name="nfx_delete_item_artifact_ix"),
        ),
        migrations.AddConstraint(
            model_name="deletionitem",
            constraint=models.UniqueConstraint(
                fields=("operation", "kind", "target_id"), name="nfx_delete_item_target_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="deletionitem",
            constraint=models.CheckConstraint(
                condition=Q(expected_size_bytes__isnull=True) | Q(expected_size_bytes__gte=0),
                name="nfx_delete_item_size_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="deletionitem",
            constraint=models.CheckConstraint(
                condition=Q(expected_version__isnull=True) | Q(expected_version__gt=0),
                name="nfx_delete_item_version_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="deletionitem",
            constraint=models.CheckConstraint(
                condition=Q(digest_prefix="") | Q(digest_prefix__regex=r"^[a-f0-9]{16}$"),
                name="nfx_delete_item_digest_ck",
            ),
        ),
    ]
